# Generated by Django 4.2.5 on 2023-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pag_Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Apellido', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=15)),
                ('usuario_email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
