# Generated by Django 4.2.5 on 2023-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuarios_delete_pag_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Apellido', models.CharField(max_length=20)),
                ('usuario_email', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=15)),
                ('Confirmar_contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
