# Generated by Django 4.2.5 on 2023-09-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tarea_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
