# Generated by Django 4.2.5 on 2023-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_completed_tarea_realizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pag_Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=200)),
            ],
        ),
    ]
