# Generated by Django 4.2.5 on 2023-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_pag_registro_delete_pag_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pag_registro',
            old_name='nombre_apellido',
            new_name='nombre_Apellido',
        ),
        migrations.AlterField(
            model_name='pag_registro',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
